// Mocks generated by Mockito 5.4.4 from annotations
// in throwtrash/test/unit/usecase/share_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:throwtrash/models/activate_response.dart' as _i6;
import 'package:throwtrash/models/calendar_model.dart' as _i10;
import 'package:throwtrash/models/trash_data.dart' as _i9;
import 'package:throwtrash/models/user.dart' as _i2;
import 'package:throwtrash/usecase/repository/activation_api_interface.dart'
    as _i3;
import 'package:throwtrash/usecase/repository/crash_report_interface.dart'
    as _i11;
import 'package:throwtrash/usecase/repository/trash_repository_interface.dart'
    as _i8;
import 'package:throwtrash/usecase/user_service_interface.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ActivationApiInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivationApiInterface extends _i1.Mock
    implements _i3.ActivationApiInterface {
  @override
  _i4.Future<String> requestActivationCode(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestActivationCode,
          [userId],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #requestActivationCode,
            [userId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #requestActivationCode,
            [userId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i6.ActivateResponse?> requestAuthorizationActivationCode(
    String? code,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestAuthorizationActivationCode,
          [
            code,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i6.ActivateResponse?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.ActivateResponse?>.value(),
      ) as _i4.Future<_i6.ActivateResponse?>);
}

/// A class which mocks [UserServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserServiceInterface extends _i1.Mock
    implements _i7.UserServiceInterface {
  @override
  _i2.User get user => (super.noSuchMethod(
        Invocation.getter(#user),
        returnValue: _FakeUser_0(
          this,
          Invocation.getter(#user),
        ),
        returnValueForMissingStub: _FakeUser_0(
          this,
          Invocation.getter(#user),
        ),
      ) as _i2.User);

  @override
  _i4.Future<bool> registerUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshUser() => (super.noSuchMethod(
        Invocation.method(
          #refreshUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getIdToken() => (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [TrashRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrashRepositoryInterface extends _i1.Mock
    implements _i8.TrashRepositoryInterface {
  @override
  _i4.Future<bool> updateTrashData(_i9.TrashData? trashData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrashData,
          [trashData],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> insertTrashData(_i9.TrashData? trashData) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTrashData,
          [trashData],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i9.TrashData>> readAllTrashData() => (super.noSuchMethod(
        Invocation.method(
          #readAllTrashData,
          [],
        ),
        returnValue: _i4.Future<List<_i9.TrashData>>.value(<_i9.TrashData>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i9.TrashData>>.value(<_i9.TrashData>[]),
      ) as _i4.Future<List<_i9.TrashData>>);

  @override
  _i4.Future<bool> deleteTrashData(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTrashData,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateLastUpdateTime(int? updateTimestamp) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastUpdateTime,
          [updateTimestamp],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getLastUpdateTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastUpdateTime,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> truncateAllTrashData() => (super.noSuchMethod(
        Invocation.method(
          #truncateAllTrashData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i10.SyncStatus> getSyncStatus() => (super.noSuchMethod(
        Invocation.method(
          #getSyncStatus,
          [],
        ),
        returnValue: _i4.Future<_i10.SyncStatus>.value(_i10.SyncStatus.NOT_YET),
        returnValueForMissingStub:
            _i4.Future<_i10.SyncStatus>.value(_i10.SyncStatus.NOT_YET),
      ) as _i4.Future<_i10.SyncStatus>);

  @override
  _i4.Future<bool> setSyncStatus(_i10.SyncStatus? syncStatus) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSyncStatus,
          [syncStatus],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [CrashReportInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashReportInterface extends _i1.Mock
    implements _i11.CrashReportInterface {
  @override
  void reportCrash(
    dynamic exception, {
    StackTrace? stackTrace,
    bool? fatal,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #reportCrash,
          [exception],
          {
            #stackTrace: stackTrace,
            #fatal: fatal,
          },
        ),
        returnValueForMissingStub: null,
      );
}
