workflows:
  ios-development:
    name: iOS Development Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - development
      ios_signing:
        distribution_type: development
        bundle_identifier: net.mythrowaway.dev
      vars:
        MAJOR: "1"
        MINOR: "3"
        BUNDLE_ID: "net.mythrowaway.dev"
        FLAVOR: "development"
      flutter: fvm
      xcode: 26.2
      cocoapods: 1.14.3
      ruby: 3.2.1
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
        - pattern: 'release'
          include: false
          source: false
        - pattern: 'main'
          include: false
          source: false
      cancel_previous_builds: false
    scripts:
      # Firebaseに必要な設定ファイルを環境変数から復元する。
      # これらはFlutterfire　CLIによって生成されるファイルであり、CLIから生成するには
      # firebase loginが必要となるため、CI/CD環境では事前に環境変数に定義しておく。
      - name: Restore firebase configurations
        script: |
          mkdir -p ios/development
          echo -n ${FIREBASE_INFO} >> ./ios/development/firebase.json
          echo -n ${GOOGLE_SERVICE_INFO_PLIST} | base64 -d >> ios/development/GoogleService-Info.plist
          echo -n ${FIREBASE_OPTIONS} | base64 -d >> lib/firebase_options.dart
          echo -n ${FIREBASE_APP_ID} >> ios/.env
          echo -n ${FLAVOR} >> ios/.env
      - name: Install flutterfire cli
        script: dart pub global activate flutterfire_cli
      # Codemagicではxcode-project use-profilesでproject.pbxproj内のbundle identifierに一致する証明書とプロビジョニングファイルを取得する
      # bundle identifierはnet.mythrowaway${appIdSuffix}の形式で記載されており一致しないと判断され、次のステップでエラーが発生する。
      # このため事前にbundle identifierをnet.mythrowaway.devに置換する
      - name: Replace bundle identifier
        script: |
          #!/bin/bash
          find **/*.xcodeproj -type f | xargs sed -i "" -E 's/PRODUCT_BUNDLE_IDENTIFIER = ".+";/PRODUCT_BUNDLE_IDENTIFIER = net.mythrowaway.dev;/g'
      # XCode15化に伴いあらかじめxcodeprojとcocoapodsをインストールしておく
      - name: Install xcodeproj
        script: gem install xcodeproj cocoapods
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Install dependencies
        script: flutter pub get
      - name: Run linter
        script: flutter analyze --no-fatal-infos
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Run unit tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --flavor development \
            --dart-define=alarmApiKey=${ALARM_API_KEY} \
            --dart-define=FLAVOR=development \
            --build-name=${MAJOR}.${MINOR}.${BUILD_NUMBER} \
            --build-number=${BUILD_NUMBER} \
            --export-options-plist=/Users/builder/export_options.plist
      - name: Upload to deploygate
        script: |
          curl \
            --url "https://deploygate.com/api/users/${DEPLOYGATE_USER_NAME}/apps" \
            -H "Authorization: Bearer ${DEPLOYGATE_API_TOKEN}" \
            -X POST \
            -F "file=@./build/ios/ipa/今日のゴミ出し.dev.ipa"
    publishing:
      slack:
        channel: '#cicd'
        notify_on_build_start: false
        notify:
          success: true
          failure: true
  ios-release:
    name: iOS Release Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      groups:
        - production
      ios_signing:
        distribution_type: app_store
        bundle_identifier: net.mythrowaway
      vars:
        MAJOR: "1"
        MINOR: "3"
        BUNDLE_ID: "net.mythrowaway"
        FLAVOR: "production"
      flutter: fvm
      xcode: 26.2
      cocoapods: 1.14.3
      ruby: 3.2.1
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'release'
          include: true
          source: false
      cancel_previous_builds: false
    scripts:
      # Firebaseに必要な設定ファイルを環境変数から復元する。
      # これらはFlutterfire　CLIによって生成されるファイルであり、CLIから生成するには
      # firebase loginが必要となるため、CI/CD環境では事前に環境変数に定義しておく。
      - name: Restore firebase configurations
        script: |
          mkdir -p ios/production
          echo -n ${FIREBASE_INFO} >> ./ios/production/firebase.json
          echo -n ${GOOGLE_SERVICE_INFO_PLIST} | base64 -d >> ios/production/GoogleService-Info.plist
          echo -n ${FIREBASE_OPTIONS} | base64 -d >> lib/firebase_options.dart
          echo -n ${FIREBASE_APP_ID} >> ios/.env
          echo -n ${FLAVOR} >> ios/.env
      - name: Install flutterfire cli
        script: dart pub global activate flutterfire_cli
      # Codemagicではxcode-project use-profilesでproject.pbxproj内のbundle identifierに一致する証明書とプロビジョニングファイルを取得する
      # bundle identifierはnet.mythrowaway${appIdSuffix}の形式で記載されており一致しないと判断され、次のステップでエラーが発生する。
      # このため事前にbundle identifierをnet.mythrowawayに置換する
      - name: Replace bundle identifier
        script: |
          #!/bin/bash
          find **/*.xcodeproj -type f | xargs sed -i "" -E 's/PRODUCT_BUNDLE_IDENTIFIER = ".+";/PRODUCT_BUNDLE_IDENTIFIER = net.mythrowaway;/g'
      # XCode15化に伴いあらかじめxcodeprojとcocoapodsをインストールしておく
      - name: Install xcodeproj
        script: gem install xcodeproj cocoapods
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Install dependencies
        script: flutter pub get
      - name: Install pods
        script: |
           find . -name "Podfile" -execdir pod install \;
      - name: Run unit tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --flavor production \
            --dart-define=FLAVOR=production \
            --dart-define=alarmApiKey=${ALARM_API_KEY} \
            --build-name=${MAJOR}.${MINOR}.${BUILD_NUMBER} \
            --build-number=${BUILD_NUMBER} \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/**/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - MyInternalTestTeam
      slack:
        channel: '#cicd'
        notify_on_build_start: false
        notify:
          success: true
          failure: true
