// Mocks generated by Mockito 5.4.6 from annotations
// in throwtrash/test/unit/viewModels/edit_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:throwtrash/models/exclude_date.dart' as _i6;
import 'package:throwtrash/models/trash_data.dart' as _i5;
import 'package:throwtrash/models/trash_search_result.dart' as _i2;
import 'package:throwtrash/usecase/repository/crash_report_interface.dart'
    as _i3;
import 'package:throwtrash/usecase/sync_result.dart' as _i9;
import 'package:throwtrash/usecase/trash_data_service_interface.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTrashImportResult_0 extends _i1.SmartFake
    implements _i2.TrashImportResult {
  _FakeTrashImportResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CrashReportInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashReportInterface extends _i1.Mock
    implements _i3.CrashReportInterface {
  @override
  void reportCrash(dynamic exception, {StackTrace? stackTrace, bool? fatal}) =>
      super.noSuchMethod(
        Invocation.method(
          #reportCrash,
          [exception],
          {#stackTrace: stackTrace, #fatal: fatal},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TrashDataServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrashDataServiceInterface extends _i1.Mock
    implements _i4.TrashDataServiceInterface {
  @override
  List<_i5.TrashData> get allTrashList =>
      (super.noSuchMethod(
            Invocation.getter(#allTrashList),
            returnValue: <_i5.TrashData>[],
            returnValueForMissingStub: <_i5.TrashData>[],
          )
          as List<_i5.TrashData>);

  @override
  List<_i6.ExcludeDate> get globalExcludeDates =>
      (super.noSuchMethod(
            Invocation.getter(#globalExcludeDates),
            returnValue: <_i6.ExcludeDate>[],
            returnValueForMissingStub: <_i6.ExcludeDate>[],
          )
          as List<_i6.ExcludeDate>);

  @override
  _i7.Future<bool> refreshTrashData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTrashData, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  String getTrashName({String? type = '', String? trashVal = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrashName, [], {
              #type: type,
              #trashVal: trashVal,
            }),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getTrashName, [], {
                #type: type,
                #trashVal: trashVal,
              }),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#getTrashName, [], {
                #type: type,
                #trashVal: trashVal,
              }),
            ),
          )
          as String);

  @override
  int getScheduleCount() =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleCount, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Future<bool> addTrashData(_i5.TrashData? trashData) =>
      (super.noSuchMethod(
            Invocation.method(#addTrashData, [trashData]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteTrashData(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrashData, [id]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i5.TrashData? getTrashDataById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTrashDataById, [id]),
            returnValueForMissingStub: null,
          )
          as _i5.TrashData?);

  @override
  _i7.Future<bool> updateTrashData(_i5.TrashData? trashData) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrashData, [trashData]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> updateGlobalExcludeDates(
    List<_i6.ExcludeDate>? excludeDates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGlobalExcludeDates, [excludeDates]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i9.SyncResult> syncTrashData() =>
      (super.noSuchMethod(
            Invocation.method(#syncTrashData, []),
            returnValue: _i7.Future<_i9.SyncResult>.value(
              _i9.SyncResult.skipped,
            ),
            returnValueForMissingStub: _i7.Future<_i9.SyncResult>.value(
              _i9.SyncResult.skipped,
            ),
          )
          as _i7.Future<_i9.SyncResult>);

  @override
  _i2.TrashSearchInputType classifySearchInput(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#classifySearchInput, [input]),
            returnValue: _i2.TrashSearchInputType.postalCode,
            returnValueForMissingStub: _i2.TrashSearchInputType.postalCode,
          )
          as _i2.TrashSearchInputType);

  @override
  _i7.Future<_i2.TrashImportResult> importTrashSchedule(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#importTrashSchedule, [input]),
            returnValue: _i7.Future<_i2.TrashImportResult>.value(
              _FakeTrashImportResult_0(
                this,
                Invocation.method(#importTrashSchedule, [input]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.TrashImportResult>.value(
              _FakeTrashImportResult_0(
                this,
                Invocation.method(#importTrashSchedule, [input]),
              ),
            ),
          )
          as _i7.Future<_i2.TrashImportResult>);

  @override
  _i7.Future<bool> shouldShowInitialSearchDialog() =>
      (super.noSuchMethod(
            Invocation.method(#shouldShowInitialSearchDialog, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> markInitialSearchDialogShown() =>
      (super.noSuchMethod(
            Invocation.method(#markInitialSearchDialogShown, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String?> consumeImportMessage() =>
      (super.noSuchMethod(
            Invocation.method(#consumeImportMessage, []),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  List<List<_i5.TrashData>> getEnableTrashList({
    required int? year,
    required int? month,
    required List<int>? targetDateList,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEnableTrashList, [], {
              #year: year,
              #month: month,
              #targetDateList: targetDateList,
            }),
            returnValue: <List<_i5.TrashData>>[],
            returnValueForMissingStub: <List<_i5.TrashData>>[],
          )
          as List<List<_i5.TrashData>>);

  @override
  List<_i5.TrashData> getTrashOfToday({
    required int? year,
    required int? month,
    required int? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrashOfToday, [], {
              #year: year,
              #month: month,
              #date: date,
            }),
            returnValue: <_i5.TrashData>[],
            returnValueForMissingStub: <_i5.TrashData>[],
          )
          as List<_i5.TrashData>);
}
