// Mocks generated by Mockito 5.4.6 from annotations
// in throwtrash/test/widget/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:throwtrash/models/account_link_info.dart' as _i3;
import 'package:throwtrash/models/exclude_date.dart' as _i6;
import 'package:throwtrash/models/trash_data.dart' as _i5;
import 'package:throwtrash/models/trash_search_result.dart' as _i2;
import 'package:throwtrash/usecase/account_link_service_interface.dart' as _i12;
import 'package:throwtrash/usecase/repository/app_config_provider_interface.dart'
    as _i14;
import 'package:throwtrash/usecase/sync_result.dart' as _i9;
import 'package:throwtrash/usecase/trash_data_service_interface.dart' as _i4;
import 'package:throwtrash/viewModels/account_link_model.dart' as _i13;
import 'package:throwtrash/viewModels/change_theme_model.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTrashImportResult_0 extends _i1.SmartFake
    implements _i2.TrashImportResult {
  _FakeTrashImportResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountLinkInfo_1 extends _i1.SmartFake
    implements _i3.AccountLinkInfo {
  _FakeAccountLinkInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrashDataServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrashDataServiceInterface extends _i1.Mock
    implements _i4.TrashDataServiceInterface {
  @override
  List<_i5.TrashData> get allTrashList =>
      (super.noSuchMethod(
            Invocation.getter(#allTrashList),
            returnValue: <_i5.TrashData>[],
            returnValueForMissingStub: <_i5.TrashData>[],
          )
          as List<_i5.TrashData>);

  @override
  List<_i6.ExcludeDate> get globalExcludeDates =>
      (super.noSuchMethod(
            Invocation.getter(#globalExcludeDates),
            returnValue: <_i6.ExcludeDate>[],
            returnValueForMissingStub: <_i6.ExcludeDate>[],
          )
          as List<_i6.ExcludeDate>);

  @override
  _i7.Future<bool> refreshTrashData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTrashData, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  String getTrashName({String? type = '', String? trashVal = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrashName, [], {
              #type: type,
              #trashVal: trashVal,
            }),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getTrashName, [], {
                #type: type,
                #trashVal: trashVal,
              }),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#getTrashName, [], {
                #type: type,
                #trashVal: trashVal,
              }),
            ),
          )
          as String);

  @override
  int getScheduleCount() =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleCount, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Future<bool> addTrashData(_i5.TrashData? trashData) =>
      (super.noSuchMethod(
            Invocation.method(#addTrashData, [trashData]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteTrashData(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrashData, [id]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i5.TrashData? getTrashDataById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTrashDataById, [id]),
            returnValueForMissingStub: null,
          )
          as _i5.TrashData?);

  @override
  _i7.Future<bool> updateTrashData(_i5.TrashData? trashData) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrashData, [trashData]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> updateGlobalExcludeDates(
    List<_i6.ExcludeDate>? excludeDates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGlobalExcludeDates, [excludeDates]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i9.SyncResult> syncTrashData() =>
      (super.noSuchMethod(
            Invocation.method(#syncTrashData, []),
            returnValue: _i7.Future<_i9.SyncResult>.value(
              _i9.SyncResult.skipped,
            ),
            returnValueForMissingStub: _i7.Future<_i9.SyncResult>.value(
              _i9.SyncResult.skipped,
            ),
          )
          as _i7.Future<_i9.SyncResult>);

  @override
  _i2.TrashSearchInputType classifySearchInput(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#classifySearchInput, [input]),
            returnValue: _i2.TrashSearchInputType.postalCode,
            returnValueForMissingStub: _i2.TrashSearchInputType.postalCode,
          )
          as _i2.TrashSearchInputType);

  @override
  _i7.Future<_i2.TrashImportResult> importTrashSchedule(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#importTrashSchedule, [input]),
            returnValue: _i7.Future<_i2.TrashImportResult>.value(
              _FakeTrashImportResult_0(
                this,
                Invocation.method(#importTrashSchedule, [input]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.TrashImportResult>.value(
              _FakeTrashImportResult_0(
                this,
                Invocation.method(#importTrashSchedule, [input]),
              ),
            ),
          )
          as _i7.Future<_i2.TrashImportResult>);

  @override
  _i7.Future<bool> shouldShowInitialSearchDialog() =>
      (super.noSuchMethod(
            Invocation.method(#shouldShowInitialSearchDialog, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> markInitialSearchDialogShown() =>
      (super.noSuchMethod(
            Invocation.method(#markInitialSearchDialogShown, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String?> consumeImportMessage() =>
      (super.noSuchMethod(
            Invocation.method(#consumeImportMessage, []),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  List<List<_i5.TrashData>> getEnableTrashList({
    required int? year,
    required int? month,
    required List<int>? targetDateList,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEnableTrashList, [], {
              #year: year,
              #month: month,
              #targetDateList: targetDateList,
            }),
            returnValue: <List<_i5.TrashData>>[],
            returnValueForMissingStub: <List<_i5.TrashData>>[],
          )
          as List<List<_i5.TrashData>>);

  @override
  List<_i5.TrashData> getTrashOfToday({
    required int? year,
    required int? month,
    required int? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrashOfToday, [], {
              #year: year,
              #month: month,
              #date: date,
            }),
            returnValue: <_i5.TrashData>[],
            returnValueForMissingStub: <_i5.TrashData>[],
          )
          as List<_i5.TrashData>);
}

/// A class which mocks [ChangeThemeModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangeThemeModel extends _i1.Mock implements _i10.ChangeThemeModel {
  @override
  bool get darkMode =>
      (super.noSuchMethod(
            Invocation.getter(#darkMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> switchDarkMode() =>
      (super.noSuchMethod(
            Invocation.method(#switchDarkMode, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AccountLinkServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountLinkServiceInterface extends _i1.Mock
    implements _i12.AccountLinkServiceInterface {
  @override
  _i7.Future<_i3.AccountLinkInfo> startLink(
    _i13.AccountLinkType? accountLinkType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startLink, [accountLinkType]),
            returnValue: _i7.Future<_i3.AccountLinkInfo>.value(
              _FakeAccountLinkInfo_1(
                this,
                Invocation.method(#startLink, [accountLinkType]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.AccountLinkInfo>.value(
              _FakeAccountLinkInfo_1(
                this,
                Invocation.method(#startLink, [accountLinkType]),
              ),
            ),
          )
          as _i7.Future<_i3.AccountLinkInfo>);

  @override
  _i7.Future<_i3.AccountLinkInfo?> getAccountLinkInfoWithCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountLinkInfoWithCode, [code]),
            returnValue: _i7.Future<_i3.AccountLinkInfo?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.AccountLinkInfo?>.value(),
          )
          as _i7.Future<_i3.AccountLinkInfo?>);
}

/// A class which mocks [AppConfigProviderInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigProviderInterface extends _i1.Mock
    implements _i14.AppConfigProviderInterface {
  @override
  String get trashApiUrl =>
      (super.noSuchMethod(
            Invocation.getter(#trashApiUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#trashApiUrl),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#trashApiUrl),
            ),
          )
          as String);

  @override
  String get mobileApiUrl =>
      (super.noSuchMethod(
            Invocation.getter(#mobileApiUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#mobileApiUrl),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#mobileApiUrl),
            ),
          )
          as String);

  @override
  String get accountLinkErrorUrl =>
      (super.noSuchMethod(
            Invocation.getter(#accountLinkErrorUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#accountLinkErrorUrl),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#accountLinkErrorUrl),
            ),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get alarmApiUrl =>
      (super.noSuchMethod(
            Invocation.getter(#alarmApiUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#alarmApiUrl),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#alarmApiUrl),
            ),
          )
          as String);
}
