#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/takah/fvm/versions/3.16.2"
export "FLUTTER_APPLICATION_PATH=/Users/takah/project/throwtrash-flutter"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/takah/project/throwtrash-flutter/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=Zmxhdm9yPWRldmVsb3BtZW50,YXBwTmFtZVN1ZmZpeD0uZGV2,YXBwSWRTdWZmaXg9LmRldg==,ZmlyZWJhc2VBcHBJZD0xOjI0ODc0MzYyODk3NTppb3M6OTM2OGYyNTgwNWYyYTBiNTVhYzQ1YQ==,Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9jZjdhOWQwODAwZjJhNWRhMTY2ZGJlMGViOWZiMjQ3NjAxODI2OWIxLw=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/takah/project/throwtrash-flutter/.dart_tool/package_config.json"
export "flavor=development"
export "appNameSuffix=.dev"
export "appIdSuffix=.dev"
export "firebaseAppId=1:248743628975:ios:9368f25805f2a0b55ac45a"
